
<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>ArchaeaMod-service</AssemblyName>
  </PropertyGroup>
  <Target Name="BuildMod" AfterTargets="Build">
    <Exec Command="&quot;$(tMLBuildServerPath)&quot; -build $(ProjectDir) -eac $(TargetPath) -define &quot;$(DefineConstants)&quot; -unsafe $(AllowUnsafeBlocks)" />
  </Target>
  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.10" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
    <PackageReference Include="System.Formats.Nrbf" Version="10.0.10" />
    <PackageReference Include="System.Reflection.Metadata" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\tUserInterface\tUserInterface.csproj" />
  </ItemGroup>
</Project>