
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>ArchaeaMod</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Remove="Jobs\Jobs\**" />
    <Compile Remove="archive\**" />
    <Compile Remove="Jobs\Items\art\**" />
    <Compile Remove="Jobs\Items\Weapon\**" />
    <EmbeddedResource Remove="archive\**" />
    <EmbeddedResource Remove="Jobs\Items\art\**" />
    <EmbeddedResource Remove="Jobs\Items\Weapon\**" />
    <None Remove="archive\**" />
    <None Remove="Jobs\Items\art\**" />
    <None Remove="Jobs\Items\Weapon\**" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Remove="en-US.hjson" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Jobs\Buffs\_Frozen.cs" />
    <Compile Remove="Jobs\Items\IronWorkbench.cs" />
    <Compile Remove="Jobs\Items\Seeded_dirt.cs" />
    <Compile Remove="Jobs\Items\Tome.cs" />
    <Compile Remove="Jobs\Projectiles\Box Diffusion.cs" />
    <Compile Remove="Jobs\Projectiles\Box Shield.cs" />
    <Compile Remove="Jobs\Projectiles\FourBox.cs" />
    <Compile Remove="Jobs\Projectiles\Frost.cs" />
    <Compile Remove="Jobs\Projectiles\OneBox.cs" />
    <Compile Remove="Jobs\Projectiles\Poison.cs" />
    <Compile Remove="TakerylProject\ProjectWorld.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Buffs\ModeLifeScale.png" />
    <None Remove="Jobs\Buffs\_Frozen.ini" />
    <None Remove="Jobs\Buffs\_Frozen.png" />
    <None Remove="Jobs\Items\Armors\BomVest.png" />
    <None Remove="Jobs\Items\IronWorkbench.ini" />
    <None Remove="Jobs\Items\IronWorkbench.png" />
    <None Remove="Jobs\Items\job_bag.png" />
    <None Remove="Jobs\Items\Seeded_dirt.ini" />
    <None Remove="Jobs\Items\Tome.ini" />
    <None Remove="Jobs\Items\Tome.png" />
    <None Remove="Jobs\Items\Tome_of_petrify.png" />
    <None Remove="Jobs\Projectiles\Box Diffusion.ini" />
    <None Remove="Jobs\Projectiles\Box Diffusion.png" />
    <None Remove="Jobs\Projectiles\Box Shield.ini" />
    <None Remove="Jobs\Projectiles\Box Shield.png" />
    <None Remove="Jobs\Projectiles\FourBox Shadow.ini" />
    <None Remove="Jobs\Projectiles\FourBox Shadow.png" />
    <None Remove="Jobs\Projectiles\FourBox.ini" />
    <None Remove="Jobs\Projectiles\FourBox.png" />
    <None Remove="Jobs\Projectiles\Frost.ini" />
    <None Remove="Jobs\Projectiles\Frost.png" />
    <None Remove="Jobs\Projectiles\OneBox Shadow.ini" />
    <None Remove="Jobs\Projectiles\OneBox Shadow.png" />
    <None Remove="Jobs\Projectiles\OneBox.ini" />
    <None Remove="Jobs\Projectiles\OneBox.png" />
    <None Remove="Jobs\Projectiles\Poison.ini" />
    <None Remove="Jobs\Projectiles\Poison.png" />
    <None Remove="NPCs\Bosses\factory_01.png" />
    <None Remove="NPCs\Bosses\factory_02.png" />
    <None Remove="NPCs\Bosses\factory_02_arm_01.png" />
    <None Remove="NPCs\Bosses\factory_02_arm_02.png" />
    <None Remove="WorldGen\Factory\Tiles\ClosedMetalDoor.png" />
    <None Remove="WorldGen\Factory\Tiles\MetalDoorOpen.png" />
    <None Remove="WorldGen\Factory\Tiles\MetalDoorOpening.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Jobs\Projectiles\art\" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\tUserInterface\tUserInterface.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Drawing.Common">
      <HintPath>lib\System.Drawing.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>